[CRITICAL]2021-06-11 12:59:42,705: 192.168.252.159:10001 <--> 192.168.252.147:60002 time out cause a error: <tcpSocket.client object at 0x000002603E95C470>
pid=17284, ppid=17852, tid=15440
Traceback (most recent call last):
  File "C:\Users\Administrator\Desktop\SVN\美维\MeiWei_back_0421\feed\main_feed.py", line 130, in _handle
    data = client.recv(6)
  File "C:\Users\Administrator\Desktop\SVN\美维\MeiWei_back_0421\common\tcpSocket.py", line 179, in recv
    recvdata = self._socket.recv(bufferLen if remainLen > bufferLen else remainLen)
socket.timeout: timed out

[CRITICAL]2021-06-11 12:59:56,871: 192.168.252.159:10001 <--> 192.168.252.147:60003 time out cause a error: <tcpSocket.client object at 0x000002603C461B38>
pid=17284, ppid=17852, tid=16704
Traceback (most recent call last):
  File "C:\Users\Administrator\Desktop\SVN\美维\MeiWei_back_0421\feed\main_feed.py", line 130, in _handle
    data = client.recv(6)
  File "C:\Users\Administrator\Desktop\SVN\美维\MeiWei_back_0421\common\tcpSocket.py", line 179, in recv
    recvdata = self._socket.recv(bufferLen if remainLen > bufferLen else remainLen)
socket.timeout: timed out

[CRITICAL]2021-06-11 13:00:05,831: 192.168.252.159:10001 <--> 192.168.252.148:60823 time out cause a error: <tcpSocket.client object at 0x000002603E95C5F8>
pid=17284, ppid=17852, tid=15288
Traceback (most recent call last):
  File "C:\Users\Administrator\Desktop\SVN\美维\MeiWei_back_0421\feed\main_feed.py", line 130, in _handle
    data = client.recv(6)
  File "C:\Users\Administrator\Desktop\SVN\美维\MeiWei_back_0421\common\tcpSocket.py", line 179, in recv
    recvdata = self._socket.recv(bufferLen if remainLen > bufferLen else remainLen)
socket.timeout: timed out

