[CRITICAL]2021-06-11 13:00:50,024: 192.168.252.159:10001 <--> 192.168.252.147:60036 time out cause a error: <tcpSocket.client object at 0x000002362D3ED940>
pid=14536, ppid=16828, tid=4260
Traceback (most recent call last):
  File "C:\Users\Administrator\Desktop\SVN\美维\MeiWei_back_0421\feed\main_feed.py", line 130, in _handle
    data = client.recv(6)
  File "C:\Users\Administrator\Desktop\SVN\美维\MeiWei_back_0421\common\tcpSocket.py", line 179, in recv
    recvdata = self._socket.recv(bufferLen if remainLen > bufferLen else remainLen)
socket.timeout: timed out

[CRITICAL]2021-06-11 13:01:04,119: 192.168.252.159:10001 <--> 192.168.252.148:60853 time out cause a error: <tcpSocket.client object at 0x000002362D3EDBA8>
pid=14536, ppid=16828, tid=15884
Traceback (most recent call last):
  File "C:\Users\Administrator\Desktop\SVN\美维\MeiWei_back_0421\feed\main_feed.py", line 130, in _handle
    data = client.recv(6)
  File "C:\Users\Administrator\Desktop\SVN\美维\MeiWei_back_0421\common\tcpSocket.py", line 179, in recv
    recvdata = self._socket.recv(bufferLen if remainLen > bufferLen else remainLen)
socket.timeout: timed out

[CRITICAL]2021-06-11 13:01:20,173: 192.168.252.159:10001 <--> 192.168.252.147:60037 time out cause a error: <tcpSocket.client object at 0x000002362D3ED908>
pid=14536, ppid=16828, tid=9092
Traceback (most recent call last):
  File "C:\Users\Administrator\Desktop\SVN\美维\MeiWei_back_0421\feed\main_feed.py", line 130, in _handle
    data = client.recv(6)
  File "C:\Users\Administrator\Desktop\SVN\美维\MeiWei_back_0421\common\tcpSocket.py", line 179, in recv
    recvdata = self._socket.recv(bufferLen if remainLen > bufferLen else remainLen)
socket.timeout: timed out

