[INFO]2021-04-27 17:12:58,673: log files at E:\projects_by_myself\backup\MeiWei_back_0421\common\log
[INFO]2021-04-27 17:12:58,674: find module account.main_account
[INFO]2021-04-27 17:12:58,679: find module agvCtrl.main_agv
[INFO]2021-04-27 17:12:58,680: find module agvDevice.main_agvDevice
[INFO]2021-04-27 17:12:58,681: find module akmCtrl.main_akmCtrl
[INFO]2021-04-27 17:12:58,682: find module alarm.main_alarm
[INFO]2021-04-27 17:12:58,683: find module auth.main_auth
[INFO]2021-04-27 17:12:58,684: find module door.main_door
[INFO]2021-04-27 17:12:58,685: find module elevator.main_elevator
[INFO]2021-04-27 17:12:58,691: find module feed.main_feed
[INFO]2021-04-27 17:12:58,692: find module feed.main_feed_0427
[INFO]2021-04-27 17:12:58,693: find module remoteio.main_remoteio
[INFO]2021-04-27 17:12:58,694: import account.main_account
[INFO]2021-04-27 17:12:58,781: import agvCtrl.main_agv
[INFO]2021-04-27 17:12:59,111: create lock <lock name:doorMgr.lock,<unlocked _thread.RLock object owner=0 count=0 at 0x0000025666296EA0>>
[INFO]2021-04-27 17:13:00,047: create lock <lock name:door.lock,<unlocked _thread.RLock object owner=0 count=0 at 0x00000256662B1420>>
[INFO]2021-04-27 17:13:00,160: create lock <lock name:timer.lock_2570111001168,<unlocked _thread.RLock object owner=0 count=0 at 0x00000256668DA3C0>>
[ERROR]2021-04-27 17:13:00,173: mqtt is disabled
[INFO]2021-04-27 17:13:00,175: mqtt: subscribe [alarm/raise/+]
[INFO]2021-04-27 17:13:00,176: mqtt: subscribe [alarm/clear/+]
[INFO]2021-04-27 17:13:03,220: Mongodb connect to 127.0.0.1 port 27017
[INFO]2021-04-27 17:13:03,253: create lock <lock name:elevatorMgr.lock,<unlocked _thread.RLock object owner=0 count=0 at 0x0000025666AECDB0>>
[WARNING]2021-04-27 17:13:03,264: use mockAgvCtrl
[INFO]2021-04-27 17:13:03,267: create lock <lock name:mapMgr.lock,<unlocked _thread.RLock object owner=0 count=0 at 0x0000025664B44360>>
[INFO]2021-04-27 17:13:03,594: create lock <lock name:agvList.g_agvLock,<unlocked _thread.RLock object owner=0 count=0 at 0x0000025666B85840>>
[INFO]2021-04-27 17:13:03,598: create lock <lock name:taskList.lock,<unlocked _thread.RLock object owner=0 count=0 at 0x0000025666C2BD80>>
[INFO]2021-04-27 17:13:03,666: charge policy 1 , fix time
[INFO]2021-04-27 17:13:03,701: create lock <lock name:agvApi.g_lock,<unlocked _thread.RLock object owner=0 count=0 at 0x0000025666C35960>>
[INFO]2021-04-27 17:13:04,248: start load map E:\projects_by_myself\backup\MeiWei_back_0421\agvCtrl\projects\test\AKM2F.smap
[DEBUG]2021-04-27 17:13:04,356: elevator thread start
[INFO]2021-04-27 17:13:04,375: load map E:\projects_by_myself\backup\MeiWei_back_0421\agvCtrl\projects\test\AKM2F.smap ,used 140 ms
[INFO]2021-04-27 17:13:04,387: start load map E:\projects_by_myself\backup\MeiWei_back_0421\agvCtrl\projects\test\akmsmt.smap
[INFO]2021-04-27 17:13:04,437: load map E:\projects_by_myself\backup\MeiWei_back_0421\agvCtrl\projects\test\akmsmt.smap ,used 61 ms
[INFO]2021-04-27 17:13:04,450: start load map E:\projects_by_myself\backup\MeiWei_back_0421\agvCtrl\projects\test\akmsmtMap.smap
[INFO]2021-04-27 17:13:04,573: load map E:\projects_by_myself\backup\MeiWei_back_0421\agvCtrl\projects\test\akmsmtMap.smap ,used 135 ms
[INFO]2021-04-27 17:13:04,584: start load map E:\projects_by_myself\backup\MeiWei_back_0421\agvCtrl\projects\test\desai-all-20191223.smap
[INFO]2021-04-27 17:13:04,730: load map E:\projects_by_myself\backup\MeiWei_back_0421\agvCtrl\projects\test\desai-all-20191223.smap ,used 155 ms
[INFO]2021-04-27 17:13:04,741: start load map E:\projects_by_myself\backup\MeiWei_back_0421\agvCtrl\projects\test\meiwei423.smap
[INFO]2021-04-27 17:13:04,793: load map E:\projects_by_myself\backup\MeiWei_back_0421\agvCtrl\projects\test\meiwei423.smap ,used 61 ms
[INFO]2021-04-27 17:13:04,805: start load map E:\projects_by_myself\backup\MeiWei_back_0421\agvCtrl\projects\test\untitled_20210420032952.smap
[INFO]2021-04-27 17:13:04,843: load map E:\projects_by_myself\backup\MeiWei_back_0421\agvCtrl\projects\test\untitled_20210420032952.smap ,used 48 ms
[INFO]2021-04-27 17:13:04,847: import agvDevice.main_agvDevice
[INFO]2021-04-27 17:13:04,850: import akmCtrl.main_akmCtrl
[INFO]2021-04-27 17:13:04,868: create lock <lock name:runTasks.g_lock,<unlocked _thread.RLock object owner=0 count=0 at 0x0000025666EBEF60>>
[INFO]2021-04-27 17:13:04,882: create lock <lock name:agvApi.g_lock,<unlocked _thread.RLock object owner=0 count=0 at 0x0000025666EE2DB0>>
[INFO]2021-04-27 17:13:04,898: create lock <lock name:runTasks.pre_lock,<unlocked _thread.RLock object owner=0 count=0 at 0x00000256697A84B0>>
[INFO]2021-04-27 17:13:04,900: create lock <lock name:timer.lock_2570160008880,<unlocked _thread.RLock object owner=0 count=0 at 0x0000025669796CF0>>
[INFO]2021-04-27 17:13:04,902: create lock <lock name:mapMgr.lock,<unlocked _thread.RLock object owner=0 count=0 at 0x000002566566E0C0>>
[INFO]2021-04-27 17:13:05,344: import alarm.main_alarm
[INFO]2021-04-27 17:13:05,345: import auth.main_auth
[INFO]2021-04-27 17:13:05,352: import door.main_door
[INFO]2021-04-27 17:13:05,355: import elevator.main_elevator
[INFO]2021-04-27 17:13:05,360: create lock <lock name:elevatorApi.g_lock,<unlocked _thread.RLock object owner=0 count=0 at 0x000002566929F600>>
[INFO]2021-04-27 17:13:05,360: import feed.main_feed
[INFO]2021-04-27 17:13:05,389: IP: 0.0.0.0 port: 10001
[INFO]2021-04-27 17:13:05,390: import feed.main_feed_0427
[INFO]2021-04-27 17:13:05,399: create lock <lock name:feedTask.g_lock,<unlocked _thread.RLock object owner=0 count=0 at 0x00000256693D82A0>>
[INFO]2021-04-27 17:13:05,445: import remoteio.main_remoteio
[SUCC]2021-04-27 17:13:05,457: utility start, pid=15564, ppid=17380
[DEBUG]2021-04-27 17:13:05,458: start timer
[INFO]2021-04-27 17:13:05,465: load agv file: E:\projects_by_myself\backup\MeiWei_back_0421\agvCtrl/projects/test/agv.cfg
[INFO]2021-04-27 17:13:05,465: create lock <lock name:agvList.AGV30.lock,<unlocked _thread.RLock object owner=0 count=0 at 0x00000256693F24E0>>
[DEBUG]2021-04-27 17:13:05,468: create aliveObj AGV30 AGV离线异常 timeout 300
[INFO]2021-04-27 17:13:05,469: AGV30 start agvList run thread
[INFO]2021-04-27 17:13:05,470: AGV30 start agvList run2 thread
[ERROR]2021-04-27 17:13:05,479: agv check init error False
[DEBUG]2021-04-27 17:13:05,480: start timer
[INFO]2021-04-27 17:13:05,486: add_ignore: taskStatus
[INFO]2021-04-27 17:13:05,486: add_ignore: api/elevator/status
[INFO]2021-04-27 17:13:05,487: add_ignore: scada/getTask
[INFO]2021-04-27 17:13:05,989: AGV30 current map meiwei423
[INFO]2021-04-27 17:13:05,993: AGV30 is online
[DEBUG]2021-04-27 17:13:06,496: GET: http://127.0.0.1:5551/api/agv/init?appName=MeiWeiTask addr: 127.0.0.1
[INFO]2021-04-27 17:13:06,497: MeiWeiTask init client agvApi
[DEBUG]2021-04-27 17:13:06,499: used 3ms 200 OK application/json;charset=utf-8, GET: http://127.0.0.1:5551/api/agv/init?appName=MeiWeiTask
[INFO]2021-04-27 17:13:06,932: tcp server [0.0.0.0][10001] ,connectedLen: 1, tcp connected : 192.168.252.237:10001 <--> 192.168.252.242:60439
[INFO]2021-04-27 17:13:07,090: **************回复线程启动**************
[DEBUG]2021-04-27 17:13:09,535: GET: http://127.0.0.1:5551/api/agv/startCharge?appName=MeiWeiTask addr: 127.0.0.1
[DEBUG]2021-04-27 17:13:09,615: used 80ms 200 OK application/json;charset=utf-8, GET: http://127.0.0.1:5551/api/agv/startCharge?appName=MeiWeiTask
[WARNING]2021-04-27 17:13:09,724: timer_thread[tid:1960] <lock name:runTasks.g_lock,<locked _thread.RLock object owner=1960 count=1 at 0x0000025666EBEF60>> ,hold 3234 ms
[INFO]2021-04-27 17:13:09,994: name=timer_thread, pid=15564, tid=1960
[01] File "E:/Users/Administrator/AppData/Local/Programs/Python/Python38/lib/threading.py", line 870, in run() 
[02] File "../common/mytimer.py", line 113, in _loop() 
[03] File "../common/lock.py", line 122, in _call() 
[04] File "../common/lock.py", line 100, in release() 
[05] File "E:/projects_by_myself/backup/MeiWei_back_0421/common/enhance.py", line 258, in getTrace() 
[06] File "E:/projects_by_myself/backup/MeiWei_back_0421/common/enhance.py", line 240, in getThreadStack()
[INFO]2021-04-27 17:13:15,723: ****************接受到的数据**************： devID: 223 keyID: 1
[CRITICAL]2021-04-27 17:13:16,407: : 192.168.252.237:10001 <--> 192.168.252.242:60439 error:  cause a error: 'int' object has no attribute 'lower'
pid=15564, ppid=17380, tid=14136
Traceback (most recent call last):
  File "E:\projects_by_myself\backup\MeiWei_back_0421\feed\main_feed.py", line 60, in _handle
    getButtonInfo(devID,keyID)
  File "E:\projects_by_myself\backup\MeiWei_back_0421\feed\main_feed.py", line 132, in getButtonInfo
    type,source,target = local.get(devID,keyID).split(",")
  File "E:\projects_by_myself\backup\MeiWei_back_0421\common\local.py", line 84, in get
    return _get_cfg().get(section,key,default)
  File "E:\projects_by_myself\backup\MeiWei_back_0421\common\config.py", line 103, in get
    if self.has_key(section,key):
  File "E:\projects_by_myself\backup\MeiWei_back_0421\common\config.py", line 93, in has_key
    if not self.has_section(section.lower()):
AttributeError: 'int' object has no attribute 'lower'

[INFO]2021-04-27 17:13:16,550: tcp server [0.0.0.0][10001] ,connectedLen: 1, disconnect:  : 192.168.252.237:10001 <--> 192.168.252.242:60439
[WARNING]2021-04-27 17:13:16,710: disconnect : 192.168.252.237:10001 <--> 192.168.252.242:60439
[INFO]2021-04-27 17:13:16,866: tcp server [0.0.0.0][10001] ,connectedLen: 2, tcp connected : 192.168.252.237:10001 <--> 192.168.252.242:60440
[INFO]2021-04-27 17:13:16,962: **************回复线程启动**************
[CRITICAL]2021-04-27 17:13:27,040: : 192.168.252.237:10001 <--> 192.168.252.242:60440 time out cause a error: <tcpSocket.client object at 0x00000256695D8CD0>
pid=15564, ppid=17380, tid=17196
Traceback (most recent call last):
  File "E:\projects_by_myself\backup\MeiWei_back_0421\feed\main_feed.py", line 51, in _handle
    data = client.recv(6)
  File "E:\projects_by_myself\backup\MeiWei_back_0421\common\tcpSocket.py", line 165, in recv
    recvdata = self._socket.recv(bufferLen if remainLen > bufferLen else remainLen)
socket.timeout: timed out

[INFO]2021-04-27 17:13:27,103: tcp server [0.0.0.0][10001] ,connectedLen: 1, disconnect:  : 192.168.252.237:10001 <--> 192.168.252.242:60440
[WARNING]2021-04-27 17:13:27,211: disconnect : 192.168.252.237:10001 <--> 192.168.252.242:60440
[INFO]2021-04-27 17:13:27,307: tcp server [0.0.0.0][10001] ,connectedLen: 1, tcp connected : 192.168.252.237:10001 <--> 192.168.252.242:60441
[INFO]2021-04-27 17:13:27,418: **************回复线程启动**************
[CRITICAL]2021-04-27 17:13:37,442: : 192.168.252.237:10001 <--> 192.168.252.242:60441 time out cause a error: <tcpSocket.client object at 0x0000025669473220>
pid=15564, ppid=17380, tid=11432
Traceback (most recent call last):
  File "E:\projects_by_myself\backup\MeiWei_back_0421\feed\main_feed.py", line 51, in _handle
    data = client.recv(6)
  File "E:\projects_by_myself\backup\MeiWei_back_0421\common\tcpSocket.py", line 165, in recv
    recvdata = self._socket.recv(bufferLen if remainLen > bufferLen else remainLen)
socket.timeout: timed out

[INFO]2021-04-27 17:13:37,510: tcp server [0.0.0.0][10001] ,connectedLen: 1, disconnect:  : 192.168.252.237:10001 <--> 192.168.252.242:60441
[WARNING]2021-04-27 17:13:37,615: disconnect : 192.168.252.237:10001 <--> 192.168.252.242:60441
[INFO]2021-04-27 17:13:37,756: tcp server [0.0.0.0][10001] ,connectedLen: 1, tcp connected : 192.168.252.237:10001 <--> 192.168.252.242:60442
[INFO]2021-04-27 17:13:37,913: **************回复线程启动**************
[INFO]2021-04-27 17:13:41,489: name=Thread-6, pid=15564, tid=8180
[01] File "E:/Users/Administrator/AppData/Local/Programs/Python/Python38/lib/threading.py", line 870, in run() 
[02] File "E:/projects_by_myself/backup/MeiWei_back_0421/feed/main_feed.py", line 51, in _handle() 
[03] File "E:/projects_by_myself/backup/MeiWei_back_0421/common/tcpSocket.py", line 165, in recv() 

name=Thread-2, pid=15564, tid=2420
[01] File "E:/Users/Administrator/AppData/Local/Programs/Python/Python38/lib/threading.py", line 870, in run() 
[02] File "../agvCtrl/agvApi.py", line 237, in _checkFinish() 

name=agv.hasDeadlock, pid=15564, tid=1196
[01] File "E:/Users/Administrator/AppData/Local/Programs/Python/Python38/lib/threading.py", line 870, in run() 
[02] File "E:/projects_by_myself/backup/MeiWei_back_0421/agvCtrl/agvControl.py", line 1024, in _threadFunc() 

name=worker 9, pid=15564, tid=656
[01] File "E:/Users/Administrator/AppData/Local/Programs/Python/Python38/lib/threading.py", line 870, in run() 
[02] File "E:/Users/Administrator/AppData/Local/Programs/Python/Python38/lib/site-packages/paste/httpserver.py", line 891, in worker_thread_callback() 
[03] File "E:/Users/Administrator/AppData/Local/Programs/Python/Python38/lib/queue.py", line 170, in get() 
[04] File "E:/Users/Administrator/AppData/Local/Programs/Python/Python38/lib/threading.py", line 302, in wait() 

name=worker 8, pid=15564, tid=5308
[01] File "E:/Users/Administrator/AppData/Local/Programs/Python/Python38/lib/threading.py", line 870, in run() 
[02] File "E:/Users/Administrator/AppData/Local/Programs/Python/Python38/lib/site-packages/paste/httpserver.py", line 891, in worker_thread_callback() 
[03] File "E:/Users/Administrator/AppData/Local/Programs/Python/Python38/lib/queue.py", line 170, in get() 
[04] File "E:/Users/Administrator/AppData/Local/Programs/Python/Python38/lib/threading.py", line 302, in wait() 

name=worker 7, pid=15564, tid=3124
[01] File "E:/Users/Administrator/AppData/Local/Programs/Python/Python38/lib/threading.py", line 870, in run() 
[02] File "E:/Users/Administrator/AppData/Local/Programs/Python/Python38/lib/site-packages/paste/httpserver.py", line 891, in worker_thread_callback() 
[03] File "E:/Users/Administrator/AppData/Local/Programs/Python/Python38/lib/queue.py", line 170, in get() 
[04] File "E:/Users/Administrator/AppData/Local/Programs/Python/Python38/lib/threading.py", line 302, in wait() 

name=worker 6, pid=15564, tid=12296
[01] File "E:/Users/Administrator/AppData/Local/Programs/Python/Python38/lib/threading.py", line 870, in run() 
[02] File "E:/Users/Administrator/AppData/Local/Programs/Python/Python38/lib/site-packages/paste/httpserver.py", line 891, in worker_thread_callback() 
[03] File "E:/Users/Administrator/AppData/Local/Programs/Python/Python38/lib/queue.py", line 170, in get() 
[04] File "E:/Users/Administrator/AppData/Local/Programs/Python/Python38/lib/threading.py", line 302, in wait() 

name=worker 5, pid=15564, tid=18184
[01] File "E:/Users/Administrator/AppData/Local/Programs/Python/Python38/lib/threading.py", line 870, in run() 
[02] File "E:/Users/Administrator/AppData/Local/Programs/Python/Python38/lib/site-packages/paste/httpserver.py", line 891, in worker_thread_callback() 
[03] File "E:/Users/Administrator/AppData/Local/Programs/Python/Python38/lib/queue.py", line 170, in get() 
[04] File "E:/Users/Administrator/AppData/Local/Programs/Python/Python38/lib/threading.py", line 302, in wait() 

name=worker 4, pid=15564, tid=1500
[01] File "E:/Users/Administrator/AppData/Local/Programs/Python/Python38/lib/threading.py", line 870, in run() 
[02] File "E:/Users/Administrator/AppData/Local/Programs/Python/Python38/lib/site-packages/paste/httpserver.py", line 891, in worker_thread_callback() 
[03] File "E:/Users/Administrator/AppData/Local/Programs/Python/Python38/lib/queue.py", line 170, in get() 
[04] File "E:/Users/Administrator/AppData/Local/Programs/Python/Python38/lib/threading.py", line 302, in wait() 

name=worker 3, pid=15564, tid=14588
[01] File "E:/Users/Administrator/AppData/Local/Programs/Python/Python38/lib/threading.py", line 870, in run() 
[02] File "E:/Users/Administrator/AppData/Local/Programs/Python/Python38/lib/site-packages/paste/httpserver.py", line 891, in worker_thread_callback() 
[03] File "E:/Users/Administrator/AppData/Local/Programs/Python/Python38/lib/queue.py", line 170, in get() 
[04] File "E:/Users/Administrator/AppData/Local/Programs/Python/Python38/lib/threading.py", line 302, in wait() 

name=worker 2, pid=15564, tid=5640
[01] File "E:/Users/Administrator/AppData/Local/Programs/Python/Python38/lib/threading.py", line 870, in run() 
[02] File "E:/Users/Administrator/AppData/Local/Programs/Python/Python38/lib/site-packages/paste/httpserver.py", line 891, in worker_thread_callback() 
[03] File "E:/Users/Administrator/AppData/Local/Programs/Python/Python38/lib/queue.py", line 170, in get() 
[04] File "E:/Users/Administrator/AppData/Local/Programs/Python/Python38/lib/threading.py", line 302, in wait() 

name=worker 1, pid=15564, tid=15000
[01] File "E:/Users/Administrator/AppData/Local/Programs/Python/Python38/lib/threading.py", line 870, in run() 
[02] File "E:/Users/Administrator/AppData/Local/Programs/Python/Python38/lib/site-packages/paste/httpserver.py", line 891, in worker_thread_callback() 
[03] File "E:/Users/Administrator/AppData/Local/Programs/Python/Python38/lib/queue.py", line 170, in get() 
[04] File "E:/Users/Administrator/AppData/Local/Programs/Python/Python38/lib/threading.py", line 302, in wait() 

name=worker 0, pid=15564, tid=1552
[01] File "E:/Users/Administrator/AppData/Local/Programs/Python/Python38/lib/threading.py", line 870, in run() 
[02] File "E:/Users/Administrator/AppData/Local/Programs/Python/Python38/lib/site-packages/paste/httpserver.py", line 891, in worker_thread_callback() 
[03] File "E:/Users/Administrator/AppData/Local/Programs/Python/Python38/lib/queue.py", line 170, in get() 
[04] File "E:/Users/Administrator/AppData/Local/Programs/Python/Python38/lib/threading.py", line 302, in wait() 

name=timer_thread, pid=15564, tid=1960
[01] File "E:/Users/Administrator/AppData/Local/Programs/Python/Python38/lib/threading.py", line 870, in run() 
[02] File "../common/mytimer.py", line 117, in _loop() 

name=agvThread2.AGV30, pid=15564, tid=5912
[01] File "E:/Users/Administrator/AppData/Local/Programs/Python/Python38/lib/threading.py", line 870, in run() 
[02] File "E:/projects_by_myself/backup/MeiWei_back_0421/agvCtrl/agvList.py", line 601, in run2() 

name=agvThread.AGV30, pid=15564, tid=1492
[01] File "E:/Users/Administrator/AppData/Local/Programs/Python/Python38/lib/threading.py", line 870, in run() 
[02] File "E:/projects_by_myself/backup/MeiWei_back_0421/agvCtrl/agvList.py", line 589, in run() 

name=timer_thread, pid=15564, tid=9312
[01] File "E:/Users/Administrator/AppData/Local/Programs/Python/Python38/lib/threading.py", line 870, in run() 
[02] File "E:/projects_by_myself/backup/MeiWei_back_0421/common/mytimer.py", line 117, in _loop() 

name=tcplisten.port_10001, pid=15564, tid=5824
[01] File "E:/Users/Administrator/AppData/Local/Programs/Python/Python38/lib/threading.py", line 870, in run() 
[02] File "E:/projects_by_myself/backup/MeiWei_back_0421/common/tcpSocket.py", line 66, in _acceptThread() 
[03] File "E:/Users/Administrator/AppData/Local/Programs/Python/Python38/lib/socket.py", line 292, in accept() 

name=Thread-1, pid=15564, tid=14292
[01] File "E:/Users/Administrator/AppData/Local/Programs/Python/Python38/lib/threading.py", line 870, in run() 
[02] File "E:/projects_by_myself/backup/MeiWei_back_0421/agvCtrl/main_agv.py", line 332, in showThread() 
[03] File "E:/projects_by_myself/backup/MeiWei_back_0421/agvCtrl/agvControl.py", line 1369, in show() 
[04] File "E:/projects_by_myself/backup/MeiWei_back_0421/agvCtrl/mainFrame.py", line 236, in show() 
[05] File "E:/projects_by_myself/backup/MeiWei_back_0421/agvCtrl/mapUI.py", line 46, in autoUpdateAgv() 
[06] File "E:/projects_by_myself/backup/MeiWei_back_0421/common/utility.py", line 167, in __call() 
[07] File "E:/projects_by_myself/backup/MeiWei_back_0421/agvCtrl/mapMgr.py", line 386, in drawAgv() 
[08] File "E:/projects_by_myself/backup/MeiWei_back_0421/agvCtrl/mapElement.py", line 380, in draw() 
[09] File "E:/projects_by_myself/backup/MeiWei_back_0421/agvCtrl/mapElement.py", line 465, in blockPath() 
[10] File "E:/projects_by_myself/backup/MeiWei_back_0421/common/local.py", line 90, in getfloat() 
[11] File "E:/projects_by_myself/backup/MeiWei_back_0421/common/local.py", line 34, in _get_cfg() 
[12] File "E:/projects_by_myself/backup/MeiWei_back_0421/common/local.py", line 29, in _loadStackFiles() 
[13] File "E:/Users/Administrator/AppData/Local/Programs/Python/Python38/lib/inspect.py", line 1526, in stack() 
[14] File "E:/Users/Administrator/AppData/Local/Programs/Python/Python38/lib/inspect.py", line 1506, in getouterframes() 
[15] File "E:/Users/Administrator/AppData/Local/Programs/Python/Python38/lib/inspect.py", line 1487, in getframeinfo() 
[16] File "E:/Users/Administrator/AppData/Local/Programs/Python/Python38/lib/inspect.py", line 706, in getsourcefile() 
[17] File "E:/Users/Administrator/AppData/Local/Programs/Python/Python38/lib/genericpath.py", line 22, in exists() 

name=door.untitled_20210420032952.ping, pid=15564, tid=8136
[01] File "E:/Users/Administrator/AppData/Local/Programs/Python/Python38/lib/threading.py", line 870, in run() 
[02] File "E:/projects_by_myself/backup/MeiWei_back_0421/agvCtrl/doorMgr.py", line 194, in check() 

name=door.untitled_20210420032952, pid=15564, tid=15812
[01] File "E:/Users/Administrator/AppData/Local/Programs/Python/Python38/lib/threading.py", line 870, in run() 
[02] File "E:/projects_by_myself/backup/MeiWei_back_0421/agvCtrl/doorMgr.py", line 185, in run() 

name=door.meiwei423.ping, pid=15564, tid=6100
[01] File "E:/Users/Administrator/AppData/Local/Programs/Python/Python38/lib/threading.py", line 870, in run() 
[02] File "E:/projects_by_myself/backup/MeiWei_back_0421/agvCtrl/doorMgr.py", line 194, in check() 

name=door.meiwei423, pid=15564, tid=15152
[01] File "E:/Users/Administrator/AppData/Local/Programs/Python/Python38/lib/threading.py", line 870, in run() 
[02] File "E:/projects_by_myself/backup/MeiWei_back_0421/agvCtrl/doorMgr.py", line 185, in run() 

name=door.desai-all-20191223.ping, pid=15564, tid=11336
[01] File "E:/Users/Administrator/AppData/Local/Programs/Python/Python38/lib/threading.py", line 870, in run() 
[02] File "E:/projects_by_myself/backup/MeiWei_back_0421/agvCtrl/doorMgr.py", line 194, in check() 

name=door.desai-all-20191223, pid=15564, tid=12800
[01] File "E:/Users/Administrator/AppData/Local/Programs/Python/Python38/lib/threading.py", line 870, in run() 
[02] File "E:/projects_by_myself/backup/MeiWei_back_0421/agvCtrl/doorMgr.py", line 185, in run() 

name=door.akmsmtMap.ping, pid=15564, tid=2708
[01] File "E:/Users/Administrator/AppData/Local/Programs/Python/Python38/lib/threading.py", line 870, in run() 
[02] File "E:/projects_by_myself/backup/MeiWei_back_0421/agvCtrl/doorMgr.py", line 194, in check() 

name=door.akmsmtMap, pid=15564, tid=1732
[01] File "E:/Users/Administrator/AppData/Local/Programs/Python/Python38/lib/threading.py", line 870, in run() 
[02] File "E:/projects_by_myself/backup/MeiWei_back_0421/agvCtrl/doorMgr.py", line 185, in run() 

name=door.akmsmt.ping, pid=15564, tid=11600
[01] File "E:/Users/Administrator/AppData/Local/Programs/Python/Python38/lib/threading.py", line 870, in run() 
[02] File "E:/projects_by_myself/backup/MeiWei_back_0421/agvCtrl/doorMgr.py", line 194, in check() 

name=door.akmsmt, pid=15564, tid=16904
[01] File "E:/Users/Administrator/AppData/Local/Programs/Python/Python38/lib/threading.py", line 870, in run() 
[02] File "E:/projects_by_myself/backup/MeiWei_back_0421/agvCtrl/doorMgr.py", line 185, in run() 

name=elevator.keep, pid=15564, tid=15136
[01] File "E:/Users/Administrator/AppData/Local/Programs/Python/Python38/lib/threading.py", line 870, in run() 
[02] File "E:/projects_by_myself/backup/MeiWei_back_0421/agvCtrl/elevatorMgr.py", line 497, in keepOpenThread() 

name=door.AKM2F.ping, pid=15564, tid=15376
[01] File "E:/Users/Administrator/AppData/Local/Programs/Python/Python38/lib/threading.py", line 870, in run() 
[02] File "E:/projects_by_myself/backup/MeiWei_back_0421/agvCtrl/doorMgr.py", line 194, in check() 

name=door.AKM2F, pid=15564, tid=14836
[01] File "E:/Users/Administrator/AppData/Local/Programs/Python/Python38/lib/threading.py", line 870, in run() 
[02] File "E:/projects_by_myself/backup/MeiWei_back_0421/agvCtrl/doorMgr.py", line 185, in run() 

name=pymongo_kill_cursors_thread, pid=15564, tid=8680
[01] File "E:/Users/Administrator/AppData/Local/Programs/Python/Python38/lib/threading.py", line 870, in run() 
[02] File "E:/Users/Administrator/AppData/Local/Programs/Python/Python38/lib/site-packages/pymongo/periodic_executor.py", line 140, in _run() 

name=pymongo_server_monitor_thread, pid=15564, tid=14320
[01] File "E:/Users/Administrator/AppData/Local/Programs/Python/Python38/lib/threading.py", line 870, in run() 
[02] File "E:/Users/Administrator/AppData/Local/Programs/Python/Python38/lib/site-packages/pymongo/periodic_executor.py", line 140, in _run() 

name=tcplisten.port_6789, pid=15564, tid=16768
[01] File "E:/Users/Administrator/AppData/Local/Programs/Python/Python38/lib/threading.py", line 870, in run() 
[02] File "E:/projects_by_myself/backup/MeiWei_back_0421/common/tcpSocket.py", line 66, in _acceptThread() 
[03] File "E:/Users/Administrator/AppData/Local/Programs/Python/Python38/lib/socket.py", line 292, in accept() 

name=MainThread, pid=15564, tid=9048
[01] File "run_all.py", line 60, in <module>() 
[02] File "E:/projects_by_myself/backup/MeiWei_back_0421/common/webutility.py", line 321, in run() 
[03] File "E:/Users/Administrator/AppData/Local/Programs/Python/Python38/lib/site-packages/bottle.py", line 3137, in run() 
[04] File "E:/Users/Administrator/AppData/Local/Programs/Python/Python38/lib/site-packages/bottle.py", line 2829, in run() 
[05] File "E:/Users/Administrator/AppData/Local/Programs/Python/Python38/lib/site-packages/paste/httpserver.py", line 1361, in serve() 
[06] File "E:/Users/Administrator/AppData/Local/Programs/Python/Python38/lib/site-packages/paste/httpserver.py", line 1107, in serve_forever() 
[07] File "E:/Users/Administrator/AppData/Local/Programs/Python/Python38/lib/socketserver.py", line 294, in handle_request() 
[08] File "E:/Users/Administrator/AppData/Local/Programs/Python/Python38/lib/selectors.py", line 323, in select() 
[09] File "E:/Users/Administrator/AppData/Local/Programs/Python/Python38/lib/selectors.py", line 314, in _select() 
[10] File "../common/utility.py", line 598, in exit() 
[11] File "E:/projects_by_myself/backup/MeiWei_back_0421/common/enhance.py", line 256, in getTrace() 
[12] File "E:/projects_by_myself/backup/MeiWei_back_0421/common/enhance.py", line 240, in getThreadStack()
[INFO]2021-04-27 17:13:41,584: lock info: count 0

try lock info: count 0
[ERROR]2021-04-27 17:13:41,692: user press Ctrl+C, print thread stack
[CRITICAL]2021-04-27 17:13:47,935: : 192.168.252.237:10001 <--> 192.168.252.242:60442 time out cause a error: <tcpSocket.client object at 0x00000256695D8CD0>
pid=15564, ppid=17380, tid=8180
Traceback (most recent call last):
  File "E:\projects_by_myself\backup\MeiWei_back_0421\feed\main_feed.py", line 51, in _handle
    data = client.recv(6)
  File "E:\projects_by_myself\backup\MeiWei_back_0421\common\tcpSocket.py", line 165, in recv
    recvdata = self._socket.recv(bufferLen if remainLen > bufferLen else remainLen)
socket.timeout: timed out

[INFO]2021-04-27 17:13:48,044: tcp server [0.0.0.0][10001] ,connectedLen: 1, disconnect:  : 192.168.252.237:10001 <--> 192.168.252.242:60442
[WARNING]2021-04-27 17:13:48,108: disconnect : 192.168.252.237:10001 <--> 192.168.252.242:60442
[INFO]2021-04-27 17:13:48,203: tcp server [0.0.0.0][10001] ,connectedLen: 1, tcp connected : 192.168.252.237:10001 <--> 192.168.252.242:60443
[INFO]2021-04-27 17:13:48,458: **************回复线程启动**************
[CRITICAL]2021-04-27 17:13:58,488: : 192.168.252.237:10001 <--> 192.168.252.242:60443 time out cause a error: <tcpSocket.client object at 0x00000256695D8F10>
pid=15564, ppid=17380, tid=5520
Traceback (most recent call last):
  File "E:\projects_by_myself\backup\MeiWei_back_0421\feed\main_feed.py", line 51, in _handle
    data = client.recv(6)
  File "E:\projects_by_myself\backup\MeiWei_back_0421\common\tcpSocket.py", line 165, in recv
    recvdata = self._socket.recv(bufferLen if remainLen > bufferLen else remainLen)
socket.timeout: timed out

[INFO]2021-04-27 17:13:58,599: tcp server [0.0.0.0][10001] ,connectedLen: 1, disconnect:  : 192.168.252.237:10001 <--> 192.168.252.242:60443
[WARNING]2021-04-27 17:13:58,679: disconnect : 192.168.252.237:10001 <--> 192.168.252.242:60443
[INFO]2021-04-27 17:13:58,775: tcp server [0.0.0.0][10001] ,connectedLen: 1, tcp connected : 192.168.252.237:10001 <--> 192.168.252.242:60444
[INFO]2021-04-27 17:13:58,965: **************回复线程启动**************
[CRITICAL]2021-04-27 17:14:09,027: : 192.168.252.237:10001 <--> 192.168.252.242:60444 time out cause a error: <tcpSocket.client object at 0x00000256695D8CD0>
pid=15564, ppid=17380, tid=15068
Traceback (most recent call last):
  File "E:\projects_by_myself\backup\MeiWei_back_0421\feed\main_feed.py", line 51, in _handle
    data = client.recv(6)
  File "E:\projects_by_myself\backup\MeiWei_back_0421\common\tcpSocket.py", line 165, in recv
    recvdata = self._socket.recv(bufferLen if remainLen > bufferLen else remainLen)
socket.timeout: timed out

[INFO]2021-04-27 17:14:09,139: tcp server [0.0.0.0][10001] ,connectedLen: 1, disconnect:  : 192.168.252.237:10001 <--> 192.168.252.242:60444
[WARNING]2021-04-27 17:14:09,219: disconnect : 192.168.252.237:10001 <--> 192.168.252.242:60444
[INFO]2021-04-27 17:14:09,362: tcp server [0.0.0.0][10001] ,connectedLen: 1, tcp connected : 192.168.252.237:10001 <--> 192.168.252.242:60445
[INFO]2021-04-27 17:14:09,474: **************回复线程启动**************
[CRITICAL]2021-04-27 17:14:19,500: : 192.168.252.237:10001 <--> 192.168.252.242:60445 time out cause a error: <tcpSocket.client object at 0x0000025669723D90>
pid=15564, ppid=17380, tid=6060
Traceback (most recent call last):
  File "E:\projects_by_myself\backup\MeiWei_back_0421\feed\main_feed.py", line 51, in _handle
    data = client.recv(6)
  File "E:\projects_by_myself\backup\MeiWei_back_0421\common\tcpSocket.py", line 165, in recv
    recvdata = self._socket.recv(bufferLen if remainLen > bufferLen else remainLen)
socket.timeout: timed out

[INFO]2021-04-27 17:14:19,655: tcp server [0.0.0.0][10001] ,connectedLen: 1, disconnect:  : 192.168.252.237:10001 <--> 192.168.252.242:60445
[WARNING]2021-04-27 17:14:19,751: disconnect : 192.168.252.237:10001 <--> 192.168.252.242:60445
[INFO]2021-04-27 17:14:19,909: tcp server [0.0.0.0][10001] ,connectedLen: 1, tcp connected : 192.168.252.237:10001 <--> 192.168.252.242:60446
[INFO]2021-04-27 17:14:20,050: **************回复线程启动**************
[CRITICAL]2021-04-27 17:14:30,122: : 192.168.252.237:10001 <--> 192.168.252.242:60446 time out cause a error: <tcpSocket.client object at 0x00000256695FCDF0>
pid=15564, ppid=17380, tid=16668
Traceback (most recent call last):
  File "E:\projects_by_myself\backup\MeiWei_back_0421\feed\main_feed.py", line 51, in _handle
    data = client.recv(6)
  File "E:\projects_by_myself\backup\MeiWei_back_0421\common\tcpSocket.py", line 165, in recv
    recvdata = self._socket.recv(bufferLen if remainLen > bufferLen else remainLen)
socket.timeout: timed out

[INFO]2021-04-27 17:14:30,232: tcp server [0.0.0.0][10001] ,connectedLen: 1, disconnect:  : 192.168.252.237:10001 <--> 192.168.252.242:60446
[WARNING]2021-04-27 17:14:30,309: disconnect : 192.168.252.237:10001 <--> 192.168.252.242:60446
[INFO]2021-04-27 17:14:30,450: tcp server [0.0.0.0][10001] ,connectedLen: 1, tcp connected : 192.168.252.237:10001 <--> 192.168.252.242:60447
[INFO]2021-04-27 17:14:30,546: **************回复线程启动**************
[ERROR]2021-04-27 17:14:32,834: user press Ctrl+C, system quit!
[WARNING]2021-04-27 17:14:32,944: runTask:stop save file
[ERROR]2021-04-27 17:14:33,007: user press Ctrl+C, system quit!
[ERROR]2021-04-27 17:14:33,087: process exited, living 0:01:28.227058 seconds
