[INFO]2021-03-03 17:24:16,963: log files at D:\python_lx\akm\common\log
[INFO]2021-03-03 17:24:16,963: find module agvCtrl.main_agv
[INFO]2021-03-03 17:24:16,964: find module agvDevice.main_agvDevice
[INFO]2021-03-03 17:24:16,964: find module alarm.main_alarm
[INFO]2021-03-03 17:24:16,964: find module auth.main_auth
[INFO]2021-03-03 17:24:16,964: find module button.main_button
[INFO]2021-03-03 17:24:16,964: find module door.main_door
[INFO]2021-03-03 17:24:16,965: find module elevator.main_elevator
[INFO]2021-03-03 17:24:16,965: find module virtualDoor.main_doorCtrl
[INFO]2021-03-03 17:24:16,965: import agvCtrl.main_agv
[INFO]2021-03-03 17:24:17,344: create lock <lock name:doorMgr.lock,<unlocked _thread.RLock object owner=0 count=0 at 0x000001BF1B6CD630>>
[INFO]2021-03-03 17:24:17,346: create lock <lock name:door.lock,<unlocked _thread.RLock object owner=0 count=0 at 0x000001BF1B6DD810>>
[INFO]2021-03-03 17:24:17,346: create lock <lock name:door.lock,<unlocked _thread.RLock object owner=0 count=0 at 0x000001BF1B6DDA20>>
[INFO]2021-03-03 17:24:17,437: create lock <lock name:timer.lock_1920313998976,<unlocked _thread.RLock object owner=0 count=0 at 0x000001BF1BA23FC0>>
[ERROR]2021-03-03 17:24:17,449: mqtt is disabled
[INFO]2021-03-03 17:24:17,449: mqtt: subscribe [alarm/raise/+]
[INFO]2021-03-03 17:24:17,449: mqtt: subscribe [alarm/clear/+]
[INFO]2021-03-03 17:24:20,476: Mongodb connect to 127.0.0.1 port 27017
[INFO]2021-03-03 17:24:20,528: create lock <lock name:elevatorApi.tcp_lock,<unlocked _thread.RLock object owner=0 count=0 at 0x000001BF1BCB73F0>>
[INFO]2021-03-03 17:24:20,529: create lock <lock name:elevatorApi.g_lock,<unlocked _thread.RLock object owner=0 count=0 at 0x000001BF1BCB0CF0>>
[INFO]2021-03-03 17:24:20,530: create lock <lock name:elevatorMgr.lock,<unlocked _thread.RLock object owner=0 count=0 at 0x000001BF1BCB0150>>
[INFO]2021-03-03 17:24:20,551: create lock <lock name:agvserver,<unlocked _thread.RLock object owner=0 count=0 at 0x000001BF1BCFC510>>
[INFO]2021-03-03 17:24:20,831: create lock <lock name:mapMgr.lock,<unlocked _thread.RLock object owner=0 count=0 at 0x000001BF1BCC2210>>
[INFO]2021-03-03 17:24:21,087: create lock <lock name:agvList.g_agvLock,<unlocked _thread.RLock object owner=0 count=0 at 0x000001BF1BD96ED0>>
[INFO]2021-03-03 17:24:21,090: create lock <lock name:taskList.lock,<unlocked _thread.RLock object owner=0 count=0 at 0x000001BF1BE508A0>>
[INFO]2021-03-03 17:24:21,148: charge policy 0 , fix time
[INFO]2021-03-03 17:24:21,193: create lock <lock name:agvApi.g_lock,<unlocked _thread.RLock object owner=0 count=0 at 0x000001BF1BE5C4B0>>
[INFO]2021-03-03 17:24:21,570: start load map D:\python_lx\akm\agvCtrl\projects\akm\AKM-AOI.smap
[DEBUG]2021-03-03 17:24:21,760: elevator thread start
[INFO]2021-03-03 17:24:21,777: load map D:\python_lx\akm\agvCtrl\projects\akm\AKM-AOI.smap ,used 215 ms
[INFO]2021-03-03 17:24:21,786: start load map D:\python_lx\akm\agvCtrl\projects\akm\AKM-DC.smap
[INFO]2021-03-03 17:24:21,840: load map D:\python_lx\akm\agvCtrl\projects\akm\AKM-DC.smap ,used 63 ms
[INFO]2021-03-03 17:24:21,847: start load map D:\python_lx\akm\agvCtrl\projects\akm\AKM-DDT.smap
[INFO]2021-03-03 17:24:21,904: load map D:\python_lx\akm\agvCtrl\projects\akm\AKM-DDT.smap ,used 64 ms
[INFO]2021-03-03 17:24:21,911: start load map D:\python_lx\akm\agvCtrl\projects\akm\AKM-FQC.smap
[DEBUG]2021-03-03 17:24:22,068: create aliveObj SK_DOOR 门控离线异常 timeout 60
[DEBUG]2021-03-03 17:24:22,068: create aliveObj vitualDoor01 门控离线异常 timeout 60
[DEBUG]2021-03-03 17:24:22,068: create aliveObj vitualDoor02 门控离线异常 timeout 60
[INFO]2021-03-03 17:24:22,087: load map D:\python_lx\akm\agvCtrl\projects\akm\AKM-FQC.smap ,used 183 ms
[INFO]2021-03-03 17:24:22,097: start load map D:\python_lx\akm\agvCtrl\projects\akm\AKM-LYH.smap
[INFO]2021-03-03 17:24:22,191: load map D:\python_lx\akm\agvCtrl\projects\akm\AKM-LYH.smap ,used 104 ms
[INFO]2021-03-03 17:24:22,200: start load map D:\python_lx\akm\agvCtrl\projects\akm\AKM-ZP.smap
[INFO]2021-03-03 17:24:22,278: load map D:\python_lx\akm\agvCtrl\projects\akm\AKM-ZP.smap ,used 86 ms
[INFO]2021-03-03 17:24:22,286: start load map D:\python_lx\akm\agvCtrl\projects\akm\office.smap
[INFO]2021-03-03 17:24:22,326: load map D:\python_lx\akm\agvCtrl\projects\akm\office.smap ,used 48 ms
[INFO]2021-03-03 17:24:22,328: import agvDevice.main_agvDevice
[INFO]2021-03-03 17:24:22,328: import alarm.main_alarm
[INFO]2021-03-03 17:24:22,329: import auth.main_auth
[INFO]2021-03-03 17:24:22,336: import button.main_button
[INFO]2021-03-03 17:24:22,340: create lock <lock name:agvApi.g_lock,<unlocked _thread.RLock object owner=0 count=0 at 0x000001BF1C370BD0>>
[INFO]2021-03-03 17:24:22,370: import door.main_door
[INFO]2021-03-03 17:24:22,372: import elevator.main_elevator
[INFO]2021-03-03 17:24:22,373: import virtualDoor.main_doorCtrl
[INFO]2021-03-03 17:24:23,547: create lock <lock name:IOAlarm.s_lock,<unlocked _thread.RLock object owner=0 count=0 at 0x000001BF1C58F5A0>>
[DEBUG]2021-03-03 17:24:23,549: create aliveObj magneticAGV01 二维码掉线异常 timeout 120
[SUCC]2021-03-03 17:24:23,559: utility start, pid=8832, ppid=14112
[DEBUG]2021-03-03 17:24:23,562: start timer
[INFO]2021-03-03 17:24:23,569: load agv file: D:\python_lx\akm\agvCtrl/projects/akm/agv.cfg
[INFO]2021-03-03 17:24:23,569: create lock <lock name:agvList.AGV23.lock,<unlocked _thread.RLock object owner=0 count=0 at 0x000001BF1D0D3F00>>
[DEBUG]2021-03-03 17:24:23,571: create aliveObj AGV23 AGV离线异常 timeout 300
[INFO]2021-03-03 17:24:23,571: AGV23 start agvList run thread
[INFO]2021-03-03 17:24:23,571: create lock <lock name:agv.AGV23.lock_status,<unlocked _thread.RLock object owner=0 count=0 at 0x000001BF1D0EEE10>>
[INFO]2021-03-03 17:24:23,572: AGV23 start agvList run2 thread
[DEBUG]2021-03-03 17:24:23,572: try connect AGV23 192.168.20.198:19204
[WARN]2021-03-03 17:24:23,575: Local server start! version 3.8.0, path D:\python_lx\akm\common, pid 8832
[INFO]2021-03-03 17:24:23,575: add_ignore: taskStatus
[INFO]2021-03-03 17:24:27,617: magneticAGV01 (0, 0, 0, 0)
[INFO]2021-03-03 17:24:30,632: magneticAGV01 (0, 0, 0, 0)
[ERROR]2021-03-03 17:24:33,573: connect AGV23 failed timed out
[DEBUG]2021-03-03 17:24:33,574: try connect AGV23 192.168.20.198:19204
[INFO]2021-03-03 17:24:33,644: startCharge is false
[INFO]2021-03-03 17:24:33,648: magneticAGV01 (1, 0, 0, 0)
[INFO]2021-03-03 17:24:34,649: magneticAGV01 try to open door 0 ['SK_DOOR'] ['vitualDoor01', 'vitualDoor02']
[INFO]2021-03-03 17:24:34,655: task [magneticAGV01] readIo get status  (1, 0, 0, 0, 0, 0, 0, 0)
[DEBUG]2021-03-03 17:24:34,656: magneticAGV01 经过门 ['SK_DOOR'] checkBeginSignal -> controlVirualDoor
[INFO]2021-03-03 17:24:35,158: try to open virual door vitualDoor01
[DEBUG]2021-03-03 17:24:35,159: send http_get: http://127.0.0.1:8999/api/switch/on?id=vitualDoor01
[DEBUG]2021-03-03 17:24:35,178: GET: http://127.0.0.1:8999/api/switch/on?id=vitualDoor01 addr: 127.0.0.1
[INFO]2021-03-03 17:24:35,179: open vitualDoor 127.0.0.100
[DEBUG]2021-03-03 17:24:35,180: used 2ms 200 OK application/json;charset=utf-8, GET: http://127.0.0.1:8999/api/switch/on?id=vitualDoor01
[DEBUG]2021-03-03 17:24:35,184: [return] use 24 ms,http_get: http://127.0.0.1:8999/api/switch/on?id=vitualDoor01
[WARN]2021-03-03 17:24:35,184: magneticAGV01 经过门 ['SK_DOOR'] controlVirualDoor error
[INFO]2021-03-03 17:24:36,666: magneticAGV01 (0, 0, 0, 0)
[INFO]2021-03-03 17:24:37,186: try to open virual door vitualDoor02
[DEBUG]2021-03-03 17:24:37,187: send http_get: http://127.0.0.1:8999/api/switch/on?id=vitualDoor02
[DEBUG]2021-03-03 17:24:37,202: GET: http://127.0.0.1:8999/api/switch/on?id=vitualDoor02 addr: 127.0.0.1
[INFO]2021-03-03 17:24:37,203: open vitualDoor 127.0.0.101
[DEBUG]2021-03-03 17:24:37,204: used 2ms 200 OK application/json;charset=utf-8, GET: http://127.0.0.1:8999/api/switch/on?id=vitualDoor02
[DEBUG]2021-03-03 17:24:37,207: [return] use 20 ms,http_get: http://127.0.0.1:8999/api/switch/on?id=vitualDoor02
[WARN]2021-03-03 17:24:37,208: magneticAGV01 经过门 ['SK_DOOR'] controlVirualDoor error
[DEBUG]2021-03-03 17:24:39,210: magneticAGV01 经过门 ['SK_DOOR'] controlVirualDoor -> opendoor
[INFO]2021-03-03 17:24:39,681: magneticAGV01 (0, 0, 0, 0)
[INFO]2021-03-03 17:24:39,713: try to open door SK_DOOR
[DEBUG]2021-03-03 17:24:39,714: send http_get: http://127.0.0.1:8999/api/switch/on?id=SK_DOOR
[DEBUG]2021-03-03 17:24:39,729: GET: http://127.0.0.1:8999/api/switch/on?id=SK_DOOR addr: 127.0.0.1
[INFO]2021-03-03 17:24:39,730: The signal to open the door has been sent,  doorIP:192.168.252.253
[DEBUG]2021-03-03 17:24:39,769: send to door module:192.168.252.253, values:outbuf[16] 55 00 00 00 00 AA 03 06 80 00 00 00 00 00 88 16
[DEBUG]2021-03-03 17:24:40,116: read from door module:192.168.252.253, values:inbuf[13] 55 00 00 00 00 AA 83 03 80 01 00 06 16
[DEBUG]2021-03-03 17:24:40,116: used 387ms 200 OK application/json;charset=utf-8, GET: http://127.0.0.1:8999/api/switch/on?id=SK_DOOR
[DEBUG]2021-03-03 17:24:40,117: [return] use 403 ms,http_get: http://127.0.0.1:8999/api/switch/on?id=SK_DOOR
[WARN]2021-03-03 17:24:40,118: magneticAGV01 经过门 ['SK_DOOR'] opendoor error
[DEBUG]2021-03-03 17:24:42,119: magneticAGV01 经过门 ['SK_DOOR'] opendoor -> leavefirst
[INFO]2021-03-03 17:24:42,689: magneticAGV01 (0, 0, 0, 0)
[ERROR]2021-03-03 17:24:43,577: connect AGV23 failed timed out
[INFO]2021-03-03 17:24:43,578: AGV23 checkLink failed 192.168.20.198 19204
[WARN]2021-03-03 17:24:43,578: agvThread.AGV23[tid:7856] <lock name:agv.AGV23.lock_status,<locked _thread.RLock object owner=7856 count=1 at 0x000001BF1D0EEE10>> ,hold 20006 ms
[INFO]2021-03-03 17:24:43,579: name=agvThread.AGV23, pid=8832, tid=7856
[01] File "C:/Python38/lib/threading.py", line 870, in run() 
[02] File "D:/python_lx/akm/agvCtrl/agvList.py", line 565, in run() 
[03] File "D:/python_lx/akm/driver/seerAgv/agvCtrl.py", line 36, in checkLink() 
[04] File "D:/python_lx/akm/driver/seerAgv/agvApi.py", line 184, in checkLink() 
[05] File "D:/python_lx/akm/common/lock.py", line 102, in release() 
[06] File "D:/python_lx/akm/common/enhance.py", line 268, in getTrace() 
[07] File "D:/python_lx/akm/common/enhance.py", line 248, in getThreadStack()
[INFO]2021-03-03 17:24:43,679: task: [magneticAGV01] readDo status  (1, 0, 0, 0, 0, 0, 0, 0)
[DEBUG]2021-03-03 17:24:43,679: magneticAGV01 经过门 ['SK_DOOR'] leavefirst -> waitAlway
[INFO]2021-03-03 17:24:44,183: task [magneticAGV01] readIo get status  (0, 0, 0, 0, 0, 0, 0, 0)
[WARN]2021-03-03 17:24:44,183: magneticAGV01 经过门 ['SK_DOOR'] waitAlway error
[DEBUG]2021-03-03 17:24:45,580: try connect AGV23 192.168.20.198:19204
[INFO]2021-03-03 17:24:45,692: startCharge is false
[INFO]2021-03-03 17:24:45,696: magneticAGV01 (0, 0, 0, 0)
[INFO]2021-03-03 17:24:46,189: task [magneticAGV01] readIo get status  (0, 0, 0, 0, 0, 0, 0, 0)
[WARN]2021-03-03 17:24:46,190: magneticAGV01 经过门 ['SK_DOOR'] waitAlway error
[INFO]2021-03-03 17:24:48,195: task [magneticAGV01] readIo get status  (0, 0, 0, 0, 0, 0, 0, 0)
[WARN]2021-03-03 17:24:48,195: magneticAGV01 经过门 ['SK_DOOR'] waitAlway error
[INFO]2021-03-03 17:24:48,711: magneticAGV01 (0, 0, 0, 0)
[INFO]2021-03-03 17:24:50,201: task [magneticAGV01] readIo get status  (0, 0, 0, 0, 0, 0, 0, 0)
[WARN]2021-03-03 17:24:50,202: magneticAGV01 经过门 ['SK_DOOR'] waitAlway error
[INFO]2021-03-03 17:24:51,719: magneticAGV01 (0, 0, 0, 0)
[INFO]2021-03-03 17:24:52,206: task [magneticAGV01] readIo get status  (0, 0, 0, 0, 0, 0, 0, 0)
[WARN]2021-03-03 17:24:52,206: magneticAGV01 经过门 ['SK_DOOR'] waitAlway error
[INFO]2021-03-03 17:24:54,212: task [magneticAGV01] readIo get status  (0, 0, 0, 0, 0, 0, 0, 0)
[WARN]2021-03-03 17:24:54,213: magneticAGV01 经过门 ['SK_DOOR'] waitAlway error
[INFO]2021-03-03 17:24:54,729: magneticAGV01 (0, 0, 0, 0)
[ERROR]2021-03-03 17:24:55,582: connect AGV23 failed timed out
[INFO]2021-03-03 17:24:55,582: AGV23 checkLink failed 192.168.20.198 19204
[WARN]2021-03-03 17:24:55,582: agvThread.AGV23[tid:7856] <lock name:agv.AGV23.lock_status,<locked _thread.RLock object owner=7856 count=1 at 0x000001BF1D0EEE10>> ,hold 10002 ms
[INFO]2021-03-03 17:24:55,583: name=agvThread.AGV23, pid=8832, tid=7856
[01] File "C:/Python38/lib/threading.py", line 870, in run() 
[02] File "D:/python_lx/akm/agvCtrl/agvList.py", line 565, in run() 
[03] File "D:/python_lx/akm/driver/seerAgv/agvCtrl.py", line 36, in checkLink() 
[04] File "D:/python_lx/akm/driver/seerAgv/agvApi.py", line 184, in checkLink() 
[05] File "D:/python_lx/akm/common/lock.py", line 102, in release() 
[06] File "D:/python_lx/akm/common/enhance.py", line 268, in getTrace() 
[07] File "D:/python_lx/akm/common/enhance.py", line 248, in getThreadStack()
[INFO]2021-03-03 17:24:56,218: task [magneticAGV01] readIo get status  (0, 0, 0, 0, 0, 0, 0, 0)
[WARN]2021-03-03 17:24:56,218: magneticAGV01 经过门 ['SK_DOOR'] waitAlway error
[DEBUG]2021-03-03 17:24:57,584: try connect AGV23 192.168.20.198:19204
[INFO]2021-03-03 17:24:57,730: startCharge is false
[INFO]2021-03-03 17:24:57,735: magneticAGV01 (0, 0, 0, 0)
[INFO]2021-03-03 17:24:58,222: task [magneticAGV01] readIo get status  (0, 0, 0, 0, 0, 0, 0, 0)
[WARN]2021-03-03 17:24:58,223: magneticAGV01 经过门 ['SK_DOOR'] waitAlway error
[INFO]2021-03-03 17:25:00,228: task [magneticAGV01] readIo get status  (0, 0, 0, 0, 0, 0, 0, 0)
[WARN]2021-03-03 17:25:00,228: magneticAGV01 经过门 ['SK_DOOR'] waitAlway error
[INFO]2021-03-03 17:25:00,750: magneticAGV01 (0, 0, 0, 0)
[INFO]2021-03-03 17:25:02,232: task [magneticAGV01] readIo get status  (0, 0, 0, 0, 0, 0, 0, 0)
[WARN]2021-03-03 17:25:02,232: magneticAGV01 经过门 ['SK_DOOR'] waitAlway error
[INFO]2021-03-03 17:25:03,760: magneticAGV01 (0, 0, 0, 0)
[INFO]2021-03-03 17:25:04,237: task [magneticAGV01] readIo get status  (0, 0, 0, 0, 0, 0, 0, 0)
[WARN]2021-03-03 17:25:04,238: magneticAGV01 经过门 ['SK_DOOR'] waitAlway error
[INFO]2021-03-03 17:25:06,243: task [magneticAGV01] readIo get status  (0, 0, 0, 0, 0, 0, 0, 0)
[WARN]2021-03-03 17:25:06,243: magneticAGV01 经过门 ['SK_DOOR'] waitAlway error
[INFO]2021-03-03 17:25:06,768: magneticAGV01 (0, 0, 0, 0)
[ERROR]2021-03-03 17:25:07,585: connect AGV23 failed timed out
[INFO]2021-03-03 17:25:07,585: AGV23 checkLink failed 192.168.20.198 19204
[WARN]2021-03-03 17:25:07,585: agvThread.AGV23[tid:7856] <lock name:agv.AGV23.lock_status,<locked _thread.RLock object owner=7856 count=1 at 0x000001BF1D0EEE10>> ,hold 10001 ms
[INFO]2021-03-03 17:25:07,586: name=agvThread.AGV23, pid=8832, tid=7856
[01] File "C:/Python38/lib/threading.py", line 870, in run() 
[02] File "D:/python_lx/akm/agvCtrl/agvList.py", line 565, in run() 
[03] File "D:/python_lx/akm/driver/seerAgv/agvCtrl.py", line 36, in checkLink() 
[04] File "D:/python_lx/akm/driver/seerAgv/agvApi.py", line 184, in checkLink() 
[05] File "D:/python_lx/akm/common/lock.py", line 102, in release() 
[06] File "D:/python_lx/akm/common/enhance.py", line 268, in getTrace() 
[07] File "D:/python_lx/akm/common/enhance.py", line 248, in getThreadStack()
[INFO]2021-03-03 17:25:08,246: task [magneticAGV01] readIo get status  (0, 0, 0, 0, 0, 0, 0, 0)
[WARN]2021-03-03 17:25:08,246: magneticAGV01 经过门 ['SK_DOOR'] waitAlway error
[DEBUG]2021-03-03 17:25:09,587: try connect AGV23 192.168.20.198:19204
[INFO]2021-03-03 17:25:09,769: startCharge is false
[INFO]2021-03-03 17:25:09,772: magneticAGV01 (0, 0, 0, 0)
[INFO]2021-03-03 17:25:10,251: task [magneticAGV01] readIo get status  (0, 0, 0, 0, 0, 0, 0, 0)
[WARN]2021-03-03 17:25:10,252: magneticAGV01 经过门 ['SK_DOOR'] waitAlway error
[INFO]2021-03-03 17:25:12,257: task [magneticAGV01] readIo get status  (0, 0, 0, 0, 0, 0, 0, 0)
[WARN]2021-03-03 17:25:12,258: magneticAGV01 经过门 ['SK_DOOR'] waitAlway error
[INFO]2021-03-03 17:25:12,788: magneticAGV01 (0, 0, 0, 0)
[INFO]2021-03-03 17:25:14,263: task [magneticAGV01] readIo get status  (0, 0, 0, 0, 0, 0, 0, 0)
[WARN]2021-03-03 17:25:14,263: magneticAGV01 经过门 ['SK_DOOR'] waitAlway error
[INFO]2021-03-03 17:25:15,799: magneticAGV01 (0, 0, 0, 0)
[INFO]2021-03-03 17:25:16,267: task [magneticAGV01] readIo get status  (0, 0, 0, 0, 0, 0, 0, 0)
[WARN]2021-03-03 17:25:16,268: magneticAGV01 经过门 ['SK_DOOR'] waitAlway error
[INFO]2021-03-03 17:25:18,272: task [magneticAGV01] readIo get status  (0, 0, 0, 0, 0, 0, 0, 0)
[WARN]2021-03-03 17:25:18,273: magneticAGV01 经过门 ['SK_DOOR'] waitAlway error
[INFO]2021-03-03 17:25:18,813: magneticAGV01 (0, 0, 0, 0)
[ERROR]2021-03-03 17:25:19,587: connect AGV23 failed timed out
[INFO]2021-03-03 17:25:19,587: AGV23 checkLink failed 192.168.20.198 19204
[WARN]2021-03-03 17:25:19,587: agvThread.AGV23[tid:7856] <lock name:agv.AGV23.lock_status,<locked _thread.RLock object owner=7856 count=1 at 0x000001BF1D0EEE10>> ,hold 10000 ms
[INFO]2021-03-03 17:25:19,588: name=agvThread.AGV23, pid=8832, tid=7856
[01] File "C:/Python38/lib/threading.py", line 870, in run() 
[02] File "D:/python_lx/akm/agvCtrl/agvList.py", line 565, in run() 
[03] File "D:/python_lx/akm/driver/seerAgv/agvCtrl.py", line 36, in checkLink() 
[04] File "D:/python_lx/akm/driver/seerAgv/agvApi.py", line 184, in checkLink() 
[05] File "D:/python_lx/akm/common/lock.py", line 102, in release() 
[06] File "D:/python_lx/akm/common/enhance.py", line 268, in getTrace() 
[07] File "D:/python_lx/akm/common/enhance.py", line 248, in getThreadStack()
[INFO]2021-03-03 17:25:20,278: task [magneticAGV01] readIo get status  (0, 0, 0, 0, 0, 0, 0, 0)
[WARN]2021-03-03 17:25:20,279: magneticAGV01 经过门 ['SK_DOOR'] waitAlway error
[DEBUG]2021-03-03 17:25:21,589: try connect AGV23 192.168.20.198:19204
[INFO]2021-03-03 17:25:21,816: startCharge is false
[INFO]2021-03-03 17:25:21,821: magneticAGV01 (0, 0, 0, 0)
[INFO]2021-03-03 17:25:22,284: task [magneticAGV01] readIo get status  (0, 0, 0, 0, 0, 0, 0, 0)
[WARN]2021-03-03 17:25:22,284: magneticAGV01 经过门 ['SK_DOOR'] waitAlway error
[INFO]2021-03-03 17:25:24,288: task [magneticAGV01] readIo get status  (0, 0, 0, 0, 0, 0, 0, 0)
[WARN]2021-03-03 17:25:24,289: magneticAGV01 经过门 ['SK_DOOR'] waitAlway error
[INFO]2021-03-03 17:25:24,844: magneticAGV01 (0, 0, 0, 0)
[INFO]2021-03-03 17:25:26,294: task [magneticAGV01] readIo get status  (0, 0, 0, 0, 0, 0, 0, 0)
[WARN]2021-03-03 17:25:26,294: magneticAGV01 经过门 ['SK_DOOR'] waitAlway error
[INFO]2021-03-03 17:25:27,853: magneticAGV01 (0, 0, 0, 0)
[INFO]2021-03-03 17:25:28,299: task [magneticAGV01] readIo get status  (0, 0, 0, 0, 0, 0, 0, 0)
[WARN]2021-03-03 17:25:28,300: magneticAGV01 经过门 ['SK_DOOR'] waitAlway error
[INFO]2021-03-03 17:25:30,305: task [magneticAGV01] readIo get status  (0, 0, 0, 0, 0, 0, 0, 0)
[WARN]2021-03-03 17:25:30,305: magneticAGV01 经过门 ['SK_DOOR'] waitAlway error
[INFO]2021-03-03 17:25:30,863: magneticAGV01 (0, 0, 0, 0)
[ERROR]2021-03-03 17:25:31,591: connect AGV23 failed timed out
[INFO]2021-03-03 17:25:31,592: AGV23 checkLink failed 192.168.20.198 19204
[WARN]2021-03-03 17:25:31,593: agvThread.AGV23[tid:7856] <lock name:agv.AGV23.lock_status,<locked _thread.RLock object owner=7856 count=1 at 0x000001BF1D0EEE10>> ,hold 10004 ms
[INFO]2021-03-03 17:25:31,595: name=agvThread.AGV23, pid=8832, tid=7856
[01] File "C:/Python38/lib/threading.py", line 870, in run() 
[02] File "D:/python_lx/akm/agvCtrl/agvList.py", line 565, in run() 
[03] File "D:/python_lx/akm/driver/seerAgv/agvCtrl.py", line 36, in checkLink() 
[04] File "D:/python_lx/akm/driver/seerAgv/agvApi.py", line 184, in checkLink() 
[05] File "D:/python_lx/akm/common/lock.py", line 102, in release() 
[06] File "D:/python_lx/akm/common/enhance.py", line 268, in getTrace() 
[07] File "D:/python_lx/akm/common/enhance.py", line 248, in getThreadStack()
[INFO]2021-03-03 17:25:32,310: task [magneticAGV01] readIo get status  (0, 0, 0, 0, 0, 0, 0, 0)
[WARN]2021-03-03 17:25:32,311: magneticAGV01 经过门 ['SK_DOOR'] waitAlway error
[DEBUG]2021-03-03 17:25:33,597: try connect AGV23 192.168.20.198:19204
[INFO]2021-03-03 17:25:33,865: startCharge is false
[INFO]2021-03-03 17:25:33,869: magneticAGV01 (0, 0, 0, 0)
[INFO]2021-03-03 17:25:34,316: task [magneticAGV01] readIo get status  (0, 0, 0, 0, 0, 0, 0, 0)
[WARN]2021-03-03 17:25:34,317: magneticAGV01 经过门 ['SK_DOOR'] waitAlway error
[INFO]2021-03-03 17:25:36,322: task [magneticAGV01] readIo get status  (0, 0, 0, 0, 0, 0, 0, 0)
[WARN]2021-03-03 17:25:36,322: magneticAGV01 经过门 ['SK_DOOR'] waitAlway error
[INFO]2021-03-03 17:25:36,884: magneticAGV01 (0, 0, 0, 0)
[INFO]2021-03-03 17:25:38,329: task [magneticAGV01] readIo get status  (0, 0, 0, 0, 0, 0, 0, 0)
[WARN]2021-03-03 17:25:38,329: magneticAGV01 经过门 ['SK_DOOR'] waitAlway error
[INFO]2021-03-03 17:25:39,892: magneticAGV01 (0, 0, 0, 0)
[INFO]2021-03-03 17:25:40,333: task [magneticAGV01] readIo get status  (0, 0, 0, 0, 0, 0, 0, 0)
[WARN]2021-03-03 17:25:40,333: magneticAGV01 经过门 ['SK_DOOR'] waitAlway error
[INFO]2021-03-03 17:25:42,338: task [magneticAGV01] readIo get status  (0, 0, 0, 0, 0, 0, 0, 0)
[WARN]2021-03-03 17:25:42,339: magneticAGV01 经过门 ['SK_DOOR'] waitAlway error
[INFO]2021-03-03 17:25:42,901: magneticAGV01 (0, 0, 0, 0)
[ERROR]2021-03-03 17:25:43,598: connect AGV23 failed timed out
[INFO]2021-03-03 17:25:43,598: AGV23 checkLink failed 192.168.20.198 19204
[WARN]2021-03-03 17:25:43,598: agvThread.AGV23[tid:7856] <lock name:agv.AGV23.lock_status,<locked _thread.RLock object owner=7856 count=1 at 0x000001BF1D0EEE10>> ,hold 10001 ms
[INFO]2021-03-03 17:25:43,599: name=agvThread.AGV23, pid=8832, tid=7856
[01] File "C:/Python38/lib/threading.py", line 870, in run() 
[02] File "D:/python_lx/akm/agvCtrl/agvList.py", line 565, in run() 
[03] File "D:/python_lx/akm/driver/seerAgv/agvCtrl.py", line 36, in checkLink() 
[04] File "D:/python_lx/akm/driver/seerAgv/agvApi.py", line 184, in checkLink() 
[05] File "D:/python_lx/akm/common/lock.py", line 102, in release() 
[06] File "D:/python_lx/akm/common/enhance.py", line 268, in getTrace() 
[07] File "D:/python_lx/akm/common/enhance.py", line 248, in getThreadStack()
[INFO]2021-03-03 17:25:44,344: task [magneticAGV01] readIo get status  (0, 0, 0, 0, 0, 0, 0, 0)
[WARN]2021-03-03 17:25:44,345: magneticAGV01 经过门 ['SK_DOOR'] waitAlway error
[DEBUG]2021-03-03 17:25:45,600: try connect AGV23 192.168.20.198:19204
[INFO]2021-03-03 17:25:45,902: startCharge is false
[INFO]2021-03-03 17:25:45,905: magneticAGV01 (0, 0, 0, 0)
[INFO]2021-03-03 17:25:46,351: task [magneticAGV01] readIo get status  (0, 0, 0, 0, 0, 0, 0, 0)
[WARN]2021-03-03 17:25:46,352: magneticAGV01 经过门 ['SK_DOOR'] waitAlway error
[INFO]2021-03-03 17:25:48,357: task [magneticAGV01] readIo get status  (0, 0, 0, 0, 0, 0, 0, 0)
[WARN]2021-03-03 17:25:48,358: magneticAGV01 经过门 ['SK_DOOR'] waitAlway error
[INFO]2021-03-03 17:25:48,920: magneticAGV01 (0, 0, 0, 0)
[INFO]2021-03-03 17:25:50,370: task [magneticAGV01] readIo get status  (0, 0, 0, 0, 0, 0, 0, 0)
[WARN]2021-03-03 17:25:50,370: magneticAGV01 经过门 ['SK_DOOR'] waitAlway error
[INFO]2021-03-03 17:25:51,927: magneticAGV01 (0, 0, 0, 0)
[INFO]2021-03-03 17:25:52,376: task [magneticAGV01] readIo get status  (0, 0, 0, 0, 0, 0, 0, 0)
[WARN]2021-03-03 17:25:52,376: magneticAGV01 经过门 ['SK_DOOR'] waitAlway error
[INFO]2021-03-03 17:25:54,386: task [magneticAGV01] readIo get status  (0, 0, 0, 0, 0, 0, 0, 0)
[WARN]2021-03-03 17:25:54,387: magneticAGV01 经过门 ['SK_DOOR'] waitAlway error
[INFO]2021-03-03 17:25:54,943: magneticAGV01 (0, 0, 0, 0)
[ERROR]2021-03-03 17:25:55,601: connect AGV23 failed timed out
[INFO]2021-03-03 17:25:55,601: AGV23 checkLink failed 192.168.20.198 19204
[WARN]2021-03-03 17:25:55,601: agvThread.AGV23[tid:7856] <lock name:agv.AGV23.lock_status,<locked _thread.RLock object owner=7856 count=1 at 0x000001BF1D0EEE10>> ,hold 10001 ms
[INFO]2021-03-03 17:25:55,602: name=agvThread.AGV23, pid=8832, tid=7856
[01] File "C:/Python38/lib/threading.py", line 870, in run() 
[02] File "D:/python_lx/akm/agvCtrl/agvList.py", line 565, in run() 
[03] File "D:/python_lx/akm/driver/seerAgv/agvCtrl.py", line 36, in checkLink() 
[04] File "D:/python_lx/akm/driver/seerAgv/agvApi.py", line 184, in checkLink() 
[05] File "D:/python_lx/akm/common/lock.py", line 102, in release() 
[06] File "D:/python_lx/akm/common/enhance.py", line 268, in getTrace() 
[07] File "D:/python_lx/akm/common/enhance.py", line 248, in getThreadStack()
[INFO]2021-03-03 17:25:56,391: task [magneticAGV01] readIo get status  (0, 0, 0, 0, 0, 0, 0, 0)
[WARN]2021-03-03 17:25:56,392: magneticAGV01 经过门 ['SK_DOOR'] waitAlway error
[DEBUG]2021-03-03 17:25:57,603: try connect AGV23 192.168.20.198:19204
[INFO]2021-03-03 17:25:57,946: startCharge is false
[INFO]2021-03-03 17:25:57,950: magneticAGV01 (0, 0, 0, 0)
[INFO]2021-03-03 17:25:58,396: task [magneticAGV01] readIo get status  (0, 0, 0, 0, 0, 0, 0, 0)
[WARN]2021-03-03 17:25:58,397: magneticAGV01 经过门 ['SK_DOOR'] waitAlway error
[INFO]2021-03-03 17:26:00,401: task [magneticAGV01] readIo get status  (0, 0, 0, 0, 0, 0, 0, 0)
[WARN]2021-03-03 17:26:00,401: magneticAGV01 经过门 ['SK_DOOR'] waitAlway error
[INFO]2021-03-03 17:26:00,960: magneticAGV01 (0, 0, 0, 0)
[INFO]2021-03-03 17:26:02,406: task [magneticAGV01] readIo get status  (0, 0, 0, 0, 0, 0, 0, 0)
[WARN]2021-03-03 17:26:02,407: magneticAGV01 经过门 ['SK_DOOR'] waitAlway error
[INFO]2021-03-03 17:26:03,975: magneticAGV01 (0, 0, 0, 0)
[INFO]2021-03-03 17:26:04,413: task [magneticAGV01] readIo get status  (0, 0, 0, 0, 0, 0, 0, 0)
[WARN]2021-03-03 17:26:04,413: magneticAGV01 经过门 ['SK_DOOR'] waitAlway error
[INFO]2021-03-03 17:26:06,419: task [magneticAGV01] readIo get status  (0, 0, 0, 0, 0, 0, 0, 0)
[WARN]2021-03-03 17:26:06,420: magneticAGV01 经过门 ['SK_DOOR'] waitAlway error
[INFO]2021-03-03 17:26:06,986: magneticAGV01 (0, 0, 0, 0)
[ERROR]2021-03-03 17:26:07,604: connect AGV23 failed timed out
[INFO]2021-03-03 17:26:07,605: AGV23 checkLink failed 192.168.20.198 19204
[WARN]2021-03-03 17:26:07,605: agvThread.AGV23[tid:7856] <lock name:agv.AGV23.lock_status,<locked _thread.RLock object owner=7856 count=1 at 0x000001BF1D0EEE10>> ,hold 10002 ms
[INFO]2021-03-03 17:26:07,608: name=agvThread.AGV23, pid=8832, tid=7856
[01] File "C:/Python38/lib/threading.py", line 870, in run() 
[02] File "D:/python_lx/akm/agvCtrl/agvList.py", line 565, in run() 
[03] File "D:/python_lx/akm/driver/seerAgv/agvCtrl.py", line 36, in checkLink() 
[04] File "D:/python_lx/akm/driver/seerAgv/agvApi.py", line 184, in checkLink() 
[05] File "D:/python_lx/akm/common/lock.py", line 102, in release() 
[06] File "D:/python_lx/akm/common/enhance.py", line 268, in getTrace() 
[07] File "D:/python_lx/akm/common/enhance.py", line 248, in getThreadStack()
[INFO]2021-03-03 17:26:08,424: task [magneticAGV01] readIo get status  (0, 0, 0, 0, 0, 0, 0, 0)
[WARN]2021-03-03 17:26:08,425: magneticAGV01 经过门 ['SK_DOOR'] waitAlway error
[DEBUG]2021-03-03 17:26:09,610: try connect AGV23 192.168.20.198:19204
[INFO]2021-03-03 17:26:09,989: startCharge is false
[INFO]2021-03-03 17:26:09,992: magneticAGV01 (0, 0, 0, 0)
[INFO]2021-03-03 17:26:10,430: task [magneticAGV01] readIo get status  (0, 0, 0, 0, 0, 0, 0, 0)
[WARN]2021-03-03 17:26:10,431: magneticAGV01 经过门 ['SK_DOOR'] waitAlway error
[INFO]2021-03-03 17:26:12,436: task [magneticAGV01] readIo get status  (0, 0, 0, 0, 0, 0, 0, 0)
[WARN]2021-03-03 17:26:12,436: magneticAGV01 经过门 ['SK_DOOR'] waitAlway error
[INFO]2021-03-03 17:26:13,006: magneticAGV01 (0, 0, 0, 0)
[INFO]2021-03-03 17:26:14,441: task [magneticAGV01] readIo get status  (0, 0, 0, 0, 0, 0, 0, 0)
[WARN]2021-03-03 17:26:14,442: magneticAGV01 经过门 ['SK_DOOR'] waitAlway error
[INFO]2021-03-03 17:26:16,024: magneticAGV01 (0, 0, 0, 0)
[INFO]2021-03-03 17:26:16,448: task [magneticAGV01] readIo get status  (0, 0, 0, 0, 0, 0, 0, 0)
[WARN]2021-03-03 17:26:16,449: magneticAGV01 经过门 ['SK_DOOR'] waitAlway error
[INFO]2021-03-03 17:26:18,455: task [magneticAGV01] readIo get status  (0, 0, 0, 0, 0, 0, 0, 0)
[WARN]2021-03-03 17:26:18,455: magneticAGV01 经过门 ['SK_DOOR'] waitAlway error
[INFO]2021-03-03 17:26:19,036: magneticAGV01 (0, 0, 0, 0)
[ERROR]2021-03-03 17:26:19,613: connect AGV23 failed timed out
[INFO]2021-03-03 17:26:19,614: AGV23 checkLink failed 192.168.20.198 19204
[WARN]2021-03-03 17:26:19,614: agvThread.AGV23[tid:7856] <lock name:agv.AGV23.lock_status,<locked _thread.RLock object owner=7856 count=1 at 0x000001BF1D0EEE10>> ,hold 10004 ms
[INFO]2021-03-03 17:26:19,617: name=agvThread.AGV23, pid=8832, tid=7856
[01] File "C:/Python38/lib/threading.py", line 870, in run() 
[02] File "D:/python_lx/akm/agvCtrl/agvList.py", line 565, in run() 
[03] File "D:/python_lx/akm/driver/seerAgv/agvCtrl.py", line 36, in checkLink() 
[04] File "D:/python_lx/akm/driver/seerAgv/agvApi.py", line 184, in checkLink() 
[05] File "D:/python_lx/akm/common/lock.py", line 102, in release() 
[06] File "D:/python_lx/akm/common/enhance.py", line 268, in getTrace() 
[07] File "D:/python_lx/akm/common/enhance.py", line 248, in getThreadStack()
[INFO]2021-03-03 17:26:20,460: task [magneticAGV01] readIo get status  (0, 0, 0, 0, 0, 0, 0, 0)
[WARN]2021-03-03 17:26:20,460: magneticAGV01 经过门 ['SK_DOOR'] waitAlway error
[DEBUG]2021-03-03 17:26:21,618: try connect AGV23 192.168.20.198:19204
[INFO]2021-03-03 17:26:22,039: startCharge is false
[INFO]2021-03-03 17:26:22,043: magneticAGV01 (0, 0, 0, 0)
[INFO]2021-03-03 17:26:22,466: task [magneticAGV01] readIo get status  (0, 0, 0, 0, 0, 0, 0, 0)
[WARN]2021-03-03 17:26:22,467: magneticAGV01 经过门 ['SK_DOOR'] waitAlway error
[INFO]2021-03-03 17:26:24,472: task [magneticAGV01] readIo get status  (0, 0, 0, 0, 0, 0, 0, 0)
[WARN]2021-03-03 17:26:24,473: magneticAGV01 经过门 ['SK_DOOR'] waitAlway error
[INFO]2021-03-03 17:26:25,051: magneticAGV01 (0, 0, 0, 0)
[INFO]2021-03-03 17:26:26,478: task [magneticAGV01] readIo get status  (0, 0, 0, 0, 0, 0, 0, 0)
[WARN]2021-03-03 17:26:26,479: magneticAGV01 经过门 ['SK_DOOR'] fail error
[INFO]2021-03-03 17:26:28,065: magneticAGV01 (0, 0, 0, 0)
[INFO]2021-03-03 17:26:28,480: try to _release virual door vitualDoor01
[DEBUG]2021-03-03 17:26:28,480: send http_get: http://127.0.0.1:8999/api/switch/off?id=vitualDoor01
[DEBUG]2021-03-03 17:26:28,481: GET: http://127.0.0.1:8999/api/switch/off?id=vitualDoor01 addr: 127.0.0.1
[INFO]2021-03-03 17:26:28,482: close vitualDoor 127.0.0.100
[DEBUG]2021-03-03 17:26:28,482: used 1ms 200 OK application/json;charset=utf-8, GET: http://127.0.0.1:8999/api/switch/off?id=vitualDoor01
[DEBUG]2021-03-03 17:26:28,483: [return] use 3 ms,http_get: http://127.0.0.1:8999/api/switch/off?id=vitualDoor01
[INFO]2021-03-03 17:26:28,984: try to _release virual door vitualDoor02
[DEBUG]2021-03-03 17:26:28,984: send http_get: http://127.0.0.1:8999/api/switch/off?id=vitualDoor02
[DEBUG]2021-03-03 17:26:28,995: GET: http://127.0.0.1:8999/api/switch/off?id=vitualDoor02 addr: 127.0.0.1
[INFO]2021-03-03 17:26:28,995: close vitualDoor 127.0.0.101
[DEBUG]2021-03-03 17:26:28,996: used 1ms 200 OK application/json;charset=utf-8, GET: http://127.0.0.1:8999/api/switch/off?id=vitualDoor02
[DEBUG]2021-03-03 17:26:28,997: [return] use 12 ms,http_get: http://127.0.0.1:8999/api/switch/off?id=vitualDoor02
[INFO]2021-03-03 17:26:29,497: task: stop
[INFO]2021-03-03 17:26:29,998: task: stop magneticAGV01 经过门 ['SK_DOOR']
[INFO]2021-03-03 17:26:31,079: magneticAGV01 (0, 0, 0, 0)
[ERROR]2021-03-03 17:26:31,621: connect AGV23 failed timed out
[INFO]2021-03-03 17:26:31,621: AGV23 checkLink failed 192.168.20.198 19204
[WARN]2021-03-03 17:26:31,621: agvThread.AGV23[tid:7856] <lock name:agv.AGV23.lock_status,<locked _thread.RLock object owner=7856 count=1 at 0x000001BF1D0EEE10>> ,hold 10003 ms
[INFO]2021-03-03 17:26:31,622: name=agvThread.AGV23, pid=8832, tid=7856
[01] File "C:/Python38/lib/threading.py", line 870, in run() 
[02] File "D:/python_lx/akm/agvCtrl/agvList.py", line 565, in run() 
[03] File "D:/python_lx/akm/driver/seerAgv/agvCtrl.py", line 36, in checkLink() 
[04] File "D:/python_lx/akm/driver/seerAgv/agvApi.py", line 184, in checkLink() 
[05] File "D:/python_lx/akm/common/lock.py", line 102, in release() 
[06] File "D:/python_lx/akm/common/enhance.py", line 268, in getTrace() 
[07] File "D:/python_lx/akm/common/enhance.py", line 248, in getThreadStack()
[DEBUG]2021-03-03 17:26:33,623: try connect AGV23 192.168.20.198:19204
[INFO]2021-03-03 17:26:34,082: startCharge is false
[INFO]2021-03-03 17:26:34,086: magneticAGV01 (0, 0, 0, 0)
[INFO]2021-03-03 17:26:37,105: magneticAGV01 (0, 0, 0, 0)
[INFO]2021-03-03 17:26:40,119: magneticAGV01 (0, 0, 0, 0)
